"""
Standalone Flask dashboard server for L5 Demand Forecasting model comparison.

Run from the project root:
    pip install flask
    python -m src.forecast_dashboard

Then open http://localhost:5000 -- pick a SKU from the dropdown and the
chart re-fetches and re-renders live (Prophet vs SARIMAX vs TimeGPT backtest).

Endpoints:
    GET /                              -> dashboard page
    GET /api/skus                      -> list of eligible SKU_IDs
    GET /api/model-comparison/<sku_id> -> chart-ready backtest JSON
    GET /api/forecast/<sku_id>         -> 5-week production forecast JSON
"""

from flask import Flask, jsonify, render_template_string, request

from src.agents.forecast.agent import DemandForecastingAgent, MIN_HISTORY_WEEKS

app = Flask(__name__)

# One shared agent instance; source tables loaded once at startup.
agent = DemandForecastingAgent()
agent._load_source_tables()

PAGE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>L5 Demand Forecasting -- Model Comparison Dashboard</title>
</head>
<body style="margin:0; padding:24px; background:#fcfcfb; font-family:-apple-system,sans-serif;">

<h2 style="font-weight:500; margin-bottom:4px;">Model comparison dashboard</h2>
<p style="color:#898781; font-size:13px; margin-top:0;">
  Backtest of Prophet, SARIMAX, and TimeGPT (if configured) on each SKU's most recent holdout window.
</p>

<div style="display:flex; align-items:center; gap:8px; margin:16px 0;">
  <label for="sku-select" style="font-size:14px; color:#52514e;">SKU:</label>
  <select id="sku-select" style="padding:6px 10px; border-radius:6px; border:1px solid #c3c2b7; font-size:14px;"></select>
  <span id="loading-indicator" style="font-size:13px; color:#898781; display:none;">Loading...</span>
</div>

<div id="model-comparison-root" style="max-width:720px;">
  <h3 style="font-weight:500; margin-bottom:4px;">Backtest: which model wins?</h3>
  <div id="model-comparison-legend" style="display:flex; flex-wrap:wrap; gap:16px; margin-bottom:12px; font-size:12px; color:#52514e;"></div>
  <div style="position:relative; width:100%; height:320px;">
    <canvas id="model-comparison-canvas"></canvas>
  </div>
  <div id="model-comparison-note" style="margin-top:12px; padding:0.75rem 1rem; background:#f4f3ef; border-radius:8px; font-size:13px; color:#52514e; display:none;"></div>
  <table id="model-comparison-scores" style="margin-top:16px; width:100%; border-collapse:collapse; font-size:13px;"></table>
</div>

<hr style="margin:32px 0; border:none; border-top:1px solid #e1e0d9;">

<div id="forecast-root" style="max-width:720px;">
  <h3 style="font-weight:500; margin-bottom:4px;">5-week forecast: baseline vs disrupted</h3>
  <p style="color:#898781; font-size:13px; margin-top:0;">Generated by the winning model (<span id="forecast-model-name">-</span>). Drag the slider to see how the disrupted forecast responds to disruption intensity.</p>

  <div style="display:flex; align-items:center; gap:12px; margin:16px 0; max-width:480px;">
    <label style="font-size:13px; color:#52514e; white-space:nowrap;">Disruption risk score</label>
    <input type="range" id="risk-slider" min="0" max="1" step="0.05" value="0.7" style="flex:1;">
    <span id="risk-value" style="font-size:13px; font-weight:600; min-width:36px;">0.70</span>
  </div>
  <div style="display:flex; align-items:center; gap:8px; margin-bottom:16px;">
    <input type="checkbox" id="disruption-active" checked>
    <label for="disruption-active" style="font-size:13px; color:#52514e;">Disruption active</label>
  </div>

  <div style="display:grid; grid-template-columns:repeat(2,1fr); gap:12px; margin-bottom:20px;">
    <div style="background:#f4f3ef; border-radius:8px; padding:1rem;">
      <p style="font-size:13px; color:#898781; margin:0 0 4px;">Expected demand drop</p>
      <p id="drop-pct-value" style="font-size:24px; font-weight:500; margin:0; color:#a32d2d;">-</p>
    </div>
    <div style="background:#f4f3ef; border-radius:8px; padding:1rem;">
      <p style="font-size:13px; color:#898781; margin:0 0 4px;">Stockout probability</p>
      <p id="stockout-prob-value" style="font-size:24px; font-weight:500; margin:0;">-</p>
    </div>
  </div>

  <div id="forecast-legend" style="display:flex; flex-wrap:wrap; gap:16px; margin-bottom:12px; font-size:12px; color:#52514e;">
    <span style="display:flex;align-items:center;gap:4px;"><span style="width:10px;height:10px;border-radius:2px;background:#2a78d6;"></span>Baseline</span>
    <span style="display:flex;align-items:center;gap:4px;"><span style="width:10px;height:10px;border-radius:2px;background:#e34948;"></span>Disrupted</span>
  </div>
  <div style="position:relative; width:100%; height:280px;">
    <canvas id="forecast-canvas"></canvas>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js"></script>
<script>
const MODEL_COLORS = { actual: "#898781", naive: "#eb6834", prophet: "#2a78d6", sarimax: "#1baf7a", timegpt: "#4a3aa7" };
let chartInstance = null;

function renderModelComparisonChart(data) {
  const legendEl = document.getElementById("model-comparison-legend");
  const noteEl = document.getElementById("model-comparison-note");
  const scoresEl = document.getElementById("model-comparison-scores");

  const datasets = [
    { key: "actual",  label: "Actual",  values: data.actual,  dash: [] },
    { key: "prophet", label: "Prophet" + (data.winner === "prophet" ? " (winner)" : ""), values: data.prophet, dash: [6,3] },
    { key: "sarimax", label: "SARIMAX" + (data.winner === "sarimax" ? " (winner)" : ""), values: data.sarimax, dash: [6,3] },
  ];
  if (data.timegpt) {
    datasets.push({ key: "timegpt", label: "TimeGPT" + (data.winner === "timegpt" ? " (winner)" : ""), values: data.timegpt, dash: [2,2] });
    noteEl.style.display = "none";
  } else {
    noteEl.style.display = "block";
    noteEl.textContent = "TimeGPT not shown: " + (data.timegpt_status || "unavailable") +
      ". Set NIXTLA_API_KEY and restart the server to include it.";
  }

  legendEl.innerHTML = datasets.map(d =>
    `<span style="display:flex;align-items:center;gap:4px;">
       <span style="width:10px;height:10px;border-radius:2px;background:${MODEL_COLORS[d.key]};"></span>${d.label}
     </span>`
  ).join("");

  if (chartInstance) chartInstance.destroy();
  chartInstance = new Chart(document.getElementById("model-comparison-canvas"), {
    type: "line",
    data: {
      labels: data.labels,
      datasets: datasets.map(d => ({
        label: d.label, data: d.values,
        borderColor: MODEL_COLORS[d.key], backgroundColor: MODEL_COLORS[d.key],
        borderWidth: d.key === "actual" ? 2 : (d.key === data.winner ? 3 : 2),
        borderDash: d.dash,
        pointRadius: d.key === "actual" || d.key === data.winner ? 4 : 3,
        tension: 0.2,
      })),
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false } },
      scales: {
        x: { grid: { display: false }, ticks: { maxRotation: 45, autoSkip: false } },
        y: { grid: { color: "#e1e0d9" }, title: { display: true, text: "Units / week" } },
      },
    },
  });

  const rows = Object.entries(data.scores).map(([model, s]) => `
    <tr style="border-bottom:1px solid #e1e0d9; ${model === data.winner ? 'font-weight:600;' : ''}">
      <td style="padding:6px 8px;">${model}${model === data.winner ? " (selected)" : ""}</td>
      <td style="padding:6px 8px; text-align:right;">${s.rmse}</td>
      <td style="padding:6px 8px; text-align:right;">${s.rmsle}</td>
      <td style="padding:6px 8px; text-align:right;">${s.smape}%</td>
      <td style="padding:6px 8px; text-align:right;">${s.mape}%</td>
      <td style="padding:6px 8px; text-align:right;">${s.latency_sec}s</td>
    </tr>`).join("");
  scoresEl.innerHTML = `
    <thead><tr style="border-bottom:2px solid #c3c2b7; font-size:12px; color:#898781; text-align:right;">
      <th style="padding:6px 8px; text-align:left;">Model</th><th style="padding:6px 8px;">RMSE</th>
      <th style="padding:6px 8px;">RMSLE</th><th style="padding:6px 8px;">SMAPE</th>
      <th style="padding:6px 8px;">MAPE</th><th style="padding:6px 8px;">Latency</th>
    </tr></thead><tbody>${rows}</tbody>`;
}

async function loadSku(skuId) {
  document.getElementById("loading-indicator").style.display = "inline";
  const res = await fetch(`/api/model-comparison/${skuId}`);
  const data = await res.json();
  renderModelComparisonChart(data);
  await loadForecast(skuId);
  document.getElementById("loading-indicator").style.display = "none";
}

let forecastChartInstance = null;

function renderForecastChart(data) {
  document.getElementById("forecast-model-name").textContent = data.model_selected;
  document.getElementById("drop-pct-value").textContent = data.expected_drop_pct + "%";
  document.getElementById("stockout-prob-value").textContent = (data.stockout_prob * 100).toFixed(1) + "%";

  const labels = data.demand_forecast.map(r => r.week_start);
  const baseline = data.demand_forecast.map(r => r.demand_baseline);
  const disrupted = data.demand_forecast.map(r => r.demand_disrupted);

  if (forecastChartInstance) forecastChartInstance.destroy();
  forecastChartInstance = new Chart(document.getElementById("forecast-canvas"), {
    type: "line",
    data: {
      labels: labels,
      datasets: [
        { label: "Baseline", data: baseline, borderColor: "#2a78d6", backgroundColor: "#2a78d6", borderWidth: 2, borderDash: [6,3], pointRadius: 4, tension: 0.2 },
        { label: "Disrupted", data: disrupted, borderColor: "#e34948", backgroundColor: "#e34948", borderWidth: 3, pointRadius: 4, tension: 0.2 },
      ],
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false } },
      scales: {
        x: { grid: { display: false } },
        y: { grid: { color: "#e1e0d9" }, title: { display: true, text: "Units / week" } },
      },
    },
  });
}

let currentSku = null;
let sliderDebounce = null;

async function loadForecast(skuId) {
  currentSku = skuId;
  const risk = document.getElementById("risk-slider").value;
  const disruptionActive = document.getElementById("disruption-active").checked ? 1 : 0;
  const res = await fetch(`/api/forecast/${skuId}?risk_score=${risk}&disruption_flag=${disruptionActive}`);
  const data = await res.json();
  if (data.error) {
    console.error(data.error);
    return;
  }
  renderForecastChart(data);
}

document.getElementById("risk-slider").addEventListener("input", (e) => {
  document.getElementById("risk-value").textContent = parseFloat(e.target.value).toFixed(2);
  clearTimeout(sliderDebounce);
  sliderDebounce = setTimeout(() => { if (currentSku) loadForecast(currentSku); }, 300);
});
document.getElementById("disruption-active").addEventListener("change", () => {
  if (currentSku) loadForecast(currentSku);
});

async function init() {
  const res = await fetch("/api/skus");
  const skus = await res.json();
  const select = document.getElementById("sku-select");
  select.innerHTML = skus.map(s => `<option value="${s}">${s}</option>`).join("");
  select.addEventListener("change", (e) => loadSku(e.target.value));
  if (skus.length) loadSku(skus[0]);
}
init();
</script>
</body>
</html>
"""


@app.route("/")
def dashboard():
    return render_template_string(PAGE)


@app.route("/api/skus")
def api_skus():
    return jsonify(agent.list_skus(min_weeks=MIN_HISTORY_WEEKS))


@app.route("/api/model-comparison/<sku_id>")
def api_model_comparison(sku_id):
    try:
        data = agent.get_model_comparison_chart_data(sku_id)
        return jsonify(data)
    except Exception as e:
        return jsonify({"error": f"{type(e).__name__}: {e}"}), 400


@app.route("/api/forecast/<sku_id>")
def api_forecast(sku_id):
    """5-week production forecast (baseline vs disrupted), using whichever
    model won that SKU's backtest. Accepts optional query params to drive
    the disruption-scenario slider on the dashboard:
        ?risk_score=0.75&disruption_flag=1
    """
    try:
        risk_score = request.args.get("risk_score", type=float)
        disruption_flag = request.args.get("disruption_flag", type=int)
        scenario = {}
        if risk_score is not None:
            scenario["risk_score_composite"] = risk_score
        if disruption_flag is not None:
            scenario["disruption_flag"] = disruption_flag

        result = agent.run(sku_id, disruption_scenario=scenario or None)
        return jsonify({
            "sku_id": result.sku_id,
            "model_selected": result.model_selected,
            "demand_forecast": result.demand_forecast,
            "expected_drop_pct": result.expected_drop_pct,
            "stockout_prob": result.stockout_prob,
            "disruption_scenario": result.disruption_scenario,
        })
    except Exception as e:
        return jsonify({"error": f"{type(e).__name__}: {e}"}), 400


if __name__ == "__main__":
    print("Dashboard running at http://localhost:5000")
    app.run(debug=False, port=5000)
